version: '3.8'

services:
    # Service pour l'application Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - .:/var/www
        ports:
            - "8000:9000"
        networks:
            - app-network
        environment:
            - MAIL_MAILER=${MAIL_MAILER}
            - MAIL_HOST=${MAIL_HOST}
            - MAIL_PORT=${MAIL_PORT}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
            - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
            - MAIL_FROM_NAME=${MAIL_FROM_NAME}
            - APP_NAME=${APP_NAME}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - APP_KEY=${APP_KEY}
            - APP_URL=${APP_URL}

    # Service pour Mailpit (si vous souhaitez tester en local avec Mailpit)
    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - app-network

    # Base de données MySQL
    db:
        image: mysql:8
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PAsSSWORD=${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
